"""baseline schema

Revision ID: 4937aa60a71f
Revises: 
Create Date: 2026-07-01 16:41:12.004671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4937aa60a71f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('nisn_nip', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('creative_projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('siswa_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ast_json', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['siswa_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('creative_projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_creative_projects_id'), ['id'], unique=False)

    op.create_table('ct_journey_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('siswa_id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('challenge_context', sa.JSON(), nullable=False),
    sa.Column('decomposition_answer_json', sa.JSON(), nullable=True),
    sa.Column('abstraction_answer_json', sa.JSON(), nullable=True),
    sa.Column('pattern_answer_json', sa.JSON(), nullable=True),
    sa.Column('algorithm_answer_json', sa.JSON(), nullable=True),
    sa.Column('ct_pre_score_json', sa.JSON(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['siswa_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ct_journey_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ct_journey_sessions_id'), ['id'], unique=False)

    op.create_table('rooms',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('guru_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('announcement', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['guru_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rooms_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_rooms_id'), ['id'], unique=False)

    op.create_table('pertemuan',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('room_id', sa.String(), nullable=False),
    sa.Column('urutan', sa.Integer(), nullable=False),
    sa.Column('judul', sa.String(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('cbl_engage_json', sa.JSON(), nullable=True),
    sa.Column('guiding_questions_json', sa.JSON(), nullable=True),
    sa.Column('reflection_questions_json', sa.JSON(), nullable=True),
    sa.Column('materi_list_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pertemuan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pertemuan_id'), ['id'], unique=False)

    op.create_table('room_members',
    sa.Column('room_id', sa.String(), nullable=False),
    sa.Column('siswa_id', sa.String(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['siswa_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_id', 'siswa_id')
    )
    op.create_table('ct_scores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('siswa_id', sa.String(), nullable=False),
    sa.Column('pertemuan_id', sa.String(), nullable=False),
    sa.Column('decomposition', sa.Integer(), nullable=False),
    sa.Column('pattern_recognition', sa.Integer(), nullable=False),
    sa.Column('abstraction', sa.Integer(), nullable=False),
    sa.Column('algorithm_design', sa.Integer(), nullable=False),
    sa.Column('composite_ct_score', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pertemuan_id'], ['pertemuan.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['siswa_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ct_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ct_scores_id'), ['id'], unique=False)

    op.create_table('learning_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pertemuan_id', sa.String(), nullable=False),
    sa.Column('judul', sa.String(), nullable=False),
    sa.Column('validator_rules_json', sa.JSON(), nullable=False),
    sa.Column('max_attempts_before_ai_hint', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pertemuan_id'], ['pertemuan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_tasks_id'), ['id'], unique=False)

    op.create_table('project_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pertemuan_id', sa.String(), nullable=False),
    sa.Column('judul', sa.String(), nullable=False),
    sa.Column('studi_kasus', sa.Text(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('rubrik_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['pertemuan_id'], ['pertemuan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_tasks_id'), ['id'], unique=False)

    op.create_table('learning_submissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('siswa_id', sa.String(), nullable=False),
    sa.Column('ast_snapshots_json', sa.JSON(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.Column('final_score', sa.Integer(), nullable=True),
    sa.Column('accuracy_score', sa.Integer(), nullable=True),
    sa.Column('efficiency_score', sa.Integer(), nullable=True),
    sa.Column('ct_session_id', sa.String(), nullable=True),
    sa.Column('reflection_answers_json', sa.JSON(), nullable=True),
    sa.Column('ct_post_score_json', sa.JSON(), nullable=True),
    sa.Column('ai_tutor_log_json', sa.JSON(), nullable=True),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ct_session_id'], ['ct_journey_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['siswa_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['learning_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_submissions_id'), ['id'], unique=False)

    op.create_table('project_submissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('siswa_id', sa.String(), nullable=False),
    sa.Column('final_ast_json', sa.JSON(), nullable=False),
    sa.Column('ct_session_id', sa.String(), nullable=True),
    sa.Column('ai_suggestion_json', sa.JSON(), nullable=True),
    sa.Column('teacher_score', sa.Integer(), nullable=True),
    sa.Column('teacher_comment', sa.Text(), nullable=True),
    sa.Column('rubrik_scores_json', sa.JSON(), nullable=True),
    sa.Column('is_published_to_gallery', sa.Boolean(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('graded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ct_session_id'], ['ct_journey_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['siswa_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['project_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_submissions_id'), ['id'], unique=False)

    op.create_table('gallery_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_submission_id', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('appreciation_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_submission_id'], ['project_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_submission_id')
    )
    with op.batch_alter_table('gallery_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gallery_items_id'), ['id'], unique=False)

    op.create_table('appreciation_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('siswa_id', sa.String(), nullable=False),
    sa.Column('gallery_item_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gallery_item_id'], ['gallery_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['siswa_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appreciation_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appreciation_logs_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appreciation_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appreciation_logs_id'))

    op.drop_table('appreciation_logs')
    with op.batch_alter_table('gallery_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gallery_items_id'))

    op.drop_table('gallery_items')
    with op.batch_alter_table('project_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_submissions_id'))

    op.drop_table('project_submissions')
    with op.batch_alter_table('learning_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_submissions_id'))

    op.drop_table('learning_submissions')
    with op.batch_alter_table('project_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_tasks_id'))

    op.drop_table('project_tasks')
    with op.batch_alter_table('learning_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_tasks_id'))

    op.drop_table('learning_tasks')
    with op.batch_alter_table('ct_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ct_scores_id'))

    op.drop_table('ct_scores')
    op.drop_table('room_members')
    with op.batch_alter_table('pertemuan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pertemuan_id'))

    op.drop_table('pertemuan')
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rooms_id'))
        batch_op.drop_index(batch_op.f('ix_rooms_code'))

    op.drop_table('rooms')
    with op.batch_alter_table('ct_journey_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ct_journey_sessions_id'))

    op.drop_table('ct_journey_sessions')
    with op.batch_alter_table('creative_projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creative_projects_id'))

    op.drop_table('creative_projects')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
