"""add ct_journey_json to learning_tasks

Revision ID: c98305a587c4
Revises: ecdafb9f0c1e
Create Date: 2026-07-02 00:04:41.175155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c98305a587c4'
down_revision: Union[str, Sequence[str], None] = 'ecdafb9f0c1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ct_journey_json', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_tasks', schema=None) as batch_op:
        batch_op.drop_column('ct_journey_json')

    # ### end Alembic commands ###
